version: 1
formatters:
  base:
    format: '%(asctime)s.%(msecs)03d :: %(levelname)-8s :: [%(filename)s:%(lineno)d] %(funcName)s - %(message)s'
    datefmt: '%Y-%m-%d:%H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: base
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: base
    filename: logconfig.log
root:
  level: DEBUG
  handlers: [console, file]